config/routes.rb
Rails.application.routes.draw do

  devise_for :user
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "posts#index"

     resources :posts do
       resources :comments, except: [:show]
       member do
         post :collect
         post :uncollect
       end
     end


      resources :users, except: [:index] do
        member do
          get :posts
          get :comments
          get :collects
          get :friends
          get :drafts
        end
      end

      resources :friendships, only: [:create, :destroy] do
        member do
          post   :accept
          delete :ignore

        end
      end

      resources :feeds, only: :index
      resources :categories, only: :show



     namespace :admin do
       resources :categories
       resources :users, only: [:index] do
         member do
          post :update
         end
       end
       root "categories#index"
     end

     namespace :api, defaults: {format: :json} do
       namespace :v1 do
         post "/login"  =>  "auth#login"
         post "/logout"  =>  "auth#logout"
         resources :posts, except: [:edit]
       end
     end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # mount_uploader :avatar, AvatarUploader

  validates_presence_of :name, :email

  before_create :generate_authentication_token

  has_many :posts, dependent: :destroy

  has_many :comments, dependent: :destroy
  has_many :commented_posts, through: :comments, source: :post

  has_many :collects, dependent: :destroy
  has_many :collected_posts, through: :collects, source: :post

  has_many :friendships, -> {where status: true}, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :inverse_friendships, -> {where status: true}, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_friendships, source: :user
  has_many :unconfirm_friendships, -> {where status: false}, class_name: "Friendship", dependent: :destroy
  has_many :unconfirm_friends, through: :unconfirm_friendships, source: :friend
  has_many :request_friendships, -> {where status: false}, class_name: "Friendship", foreign_key: "friend_id", dependent: :destroy
  has_many :request_friends, through: :request_friendships, source: :user

  def admin?
    self.role == "admin"
  end

  def all_friends
    friends = self.friends + self.inverse_friends
    return friends.uniq
  end

  def friend?(user)
    self.friends.include?(user) || self.inverse_friends.include?(user)
  end

  def unconfirm_friend?(user)
    self.unconfirm_friends.include?(user)
  end

  def request_friend?(user)
    self.request_friends.include?(user)
  end

  def generate_authentication_token
    self.authentication_token = Devise.friendly_token
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
    @users = User.page(params[:page]).per(10).order("created_at DESC")

  end

  def update
    @user = User.find(params[:id])
    @user.role = params[:role]
    @user.save!
    flash[:notice] = "User role was successfully changed !"
    redirect_back(fallback_location: admin_users_path)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :comments, :collects, :friends, :check_user, :drafts]
  before_action :set_posts
  before_action :check_user, except: [:show, :comments]

    def show

    end

    def edit

    end

    def update
     if @user.update(user_params)
       redirect_to user_path(@user)
     else
       render :action => :edit
     end
    end

    def comments
      @comments = @user.comments.includes(:post)
    end

    def collects
      @collected_posts = @user.collected_posts.includes(:collected_users)
    end

    # def drafts
    #   @drafts = @user.posts.where(public: false)
    # end

    def friends
      @friends = @user.all_friends
      @unconfirm_friends = @user.unconfirm_friends
      @request_friends = @user.request_friends
    end

private

   def set_user
    @user = User.find(params[:id])
   end

   def user_params
     params.require(:user).permit(:name, :intro, :avatar)
   end

   def check_user
     unless @user == current_user
       flash[:alert] = "You have no authority！"
       redirect_to user_path(@user)
     end
   end

   def set_posts
     @posts = Post.where(user_id: @user.id)
   end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/collects.html.erb
<%= render partial: "shared/user_profile", locals: { user: @user } %>
<%= render partial: "shared/navtab_user", locals: { user: @user } %>
<div class="container">
  <div class="row">
    <table class="table table-hover bg-light">
      <tbody>
        <% @collected_posts.each do |post| %>
          <tr>
            <td><%= link_to post.title, post_path(post) %></td>
            <td>
              <%= render partial: "shared/collect_button", locals: { post: post } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/comments.html.erb
<%= render partial: "shared/user_profile", locals: { user: @user } %>
<%= render partial: "shared/navtab_user", locals: { user: @user } %>
<div class="container">
  <div class="row">
    <% @comments.each do |comment| %>
      <div class="col-sm-12 border-top border-buttom bg-light">
        <div class="row align-items-center">
          <div class="col-sm-8 offset-sm-2" data-link="<%= post_path(comment.post) %>">
            <h4 class="m-3"><%= link_to comment.post.title, post_path(comment.post)%></h4>
            <p class="border p-4 rounded bg-white text-black"><%= comment.content %></p>
          </div>
          <!-- <div class="comment-edit-form">
              <%= form_for [comment.post, comment], remote: true do |f| %>
                <div class="form-group">
                  <div>
                    <%= f.text_area :content, maxlength: 140, class: "form-control"%>
                  </div>
                </div>
                <button type="button" class="btn btn-danger btn-sm reply-cancel-btn">Cancel</button>
                <%= f.submit 'Update', remote: true, class: "btn btn-primary btn-sm" %>
              <% end %>
            </div>
            <div class="edit-delete-group">
            <button class="btn btn-primary btn-sm reply-edit-btn glyphicon glyphicon-pencil"></button>
            <%= link_to post_comment_path(comment.post, comment), method: :delete, data: {confirm: "Are you sure to delete this comment?"} do %>
              <button class="btn btn-danger btn-sm glyphicon glyphicon-trash"></button>
            <% end %>
          </div> -->

            <!-- <tr id="comment-edit-my_comment"><%= comment.id %></tr>
            <%#= render partial: "shared/my_comments", locals: { comment: comment } %> -->
          <div class="col-sm-2">
            <%= render partial: "shared/edit_button", locals: { type: "Comment", post: comment.post, comment: comment } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/drafts.html.erb
<%= render partial: "shared/user_profile", locals: { user: @user } %>
<%= render partial: "shared/navtab_user", locals: { user: @user } %>
<div class="container">
  <div class="row">
    <table class="table table-hover text-center bg-light">
      <tbody>
        <% @user.posts.each do |post| %>
          <% if !post %>
            <em>There is no draft.</em>
          <% elsif post.draft == true %>
            <% if current_user == post.user %>
              <tr>
                <td style = "text-align: start;" > <%= link_to post.title, post_path(post), style: "margin-left: 10px"  %> <%= render partial: "shared/post_authority", locals: {post: post} %></td>
                <td>
                  <%= post.draft ? 'Draft' : 'Published' %>
                </td>
                <td><%= post.updated_at.strftime("%Y-%m-%d") %></td>
                <td>
                  <%= render partial: "shared/edit_button", locals: { type: "Post", post: post } %>
                </td>
              </tr>
            <% end %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
   <div class="col-sm-12 mt-3">
    <% if @user.errors.any? %>
      <h4>We have some errors here !</h4>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <hr>
     <% end %>
    <h2> Edit Profile </h2>
    <tr>
    <%= form_for [@user] do |f| %>
      <div class="form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :intro, "About you" %>
        <%= f.text_area :intro, class: "form-control" %>
      </div>

      <%= f.label :avatar, "Avatar" %>
      <div class="form-group">
        <%#= image_tag @user.avatar if @user.avatar? %>
        <%#= f.file_field :avatar %>
        <%= f.filestack_field :avatar, 'Upload Your Avatar!',  pickerOptions: { accept: 'image/*'} %>
      </div>

      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Cancel", user_path(@user), class: "btn btn-default" %>
      </div>
    <% end %>
    </tr>
   </div>
  </div>
</div>

app/views/users/friends.html.erb
<%= render partial: "shared/user_profile", locals: { user: @user } %>
<%= render partial: "shared/navtab_user", locals: { user: @user } %>
<div class="container border bg-light">
  <h5 class="text-center">
    Waiting for friends response
  </h5>
  <div class="row" id="wait-friend">
    <% @unconfirm_friends.each do |user| %>
      <div class="col-sm-2" id="user-<%= user.id %>">
        <%= render partial: "shared/friend_profile", locals: { user: user } %>
      </div>
    <% end %>
  </div>
</div>
<div class="container border bg-white">
  <h5 class="text-center text-black">
    My Friend request
  </h5>
  <div class="row" id="unaccept-friend">
    <% @request_friends.each do |user| %>
      <div class="col-sm-2" id="user-<%= user.id %>">
        <%= render partial: "shared/friend_profile", locals: { user: user } %>
      </div>
    <% end %>
  </div>
</div>
<div class="container border bg-light">
  <h5 class="text-center">
    Friend list
  </h5>
  <div class="row" id="friend">
    <% @friends.each do |user| %>
      <div class="col-sm-2" id="user-<%= user.id %>">
        <%= render partial: "shared/friend_profile", locals: { user: user } %>
        <%= link_to friendship_path(user), method: :delete, data: { confirm: "Are you sure to delete the friend?"}, remote: true do %>
              <button class="btn btn-danger pull-right">Delete</button>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= render partial: "shared/user_profile", locals: { user: @user } %>
<%= render partial: "shared/navtab_user", locals: { user: @user } %>
<div class="container">
  <div class="row">
    <table class="table table-hover table-borderless bg-light">
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <% if post.draft == false %>
              <% if current_user != @user && current_user.role != 'admin' %>
                <% if post.authority == 'friend' && !current_user.friend?(@user) %>
                <% elsif post.authority == 'myself' %>
                <% else %>
                  <tr>
                    <td style="text-align: start;"><%= link_to post.title, post_path(post), style: "margin-left: 10px" %> <%= render partial: "shared/post_authority", locals: {post: post} %></td>
                    <td >
                      <%= post.draft ? 'Draft' : 'Published' %>
                    </td>
                    <td ><%= post.created_at.strftime("%Y-%m-%d %H:%M") %></td>
                    <td>
                      <%= render partial: "shared/edit_button", locals: { type: "Post", post: post } %>
                    </td>
                  </tr>
                <% end%>
              <% elsif current_user.role == 'admin' && current_user != @user %>
                <% if post.authority == 'myself' %>
                <% else %>
                  <tr>
                    <td style="text-align: start;"><%= link_to post.title, post_path(post), style: "margin-left: 10px" %> <%= render partial: "shared/post_authority", locals: {post: post} %></td>
                    <td>
                      <%= post.draft ? 'Draft' : 'Published' %>
                    </td>
                    <td><%= post.created_at.strftime("%Y-%m-%d %H:%M") %></td>
                    <td>
                      <%= render partial: "shared/edit_button", locals: { type: "Post", post: post } %>
                    </td>
                  </tr>
                <% end%>
              <% else %>
                <tr>
                  <td style="text-align: start;"><%= link_to post.title, post_path(post), style: "margin-left: 10px" %> <%= render partial: "shared/post_authority", locals: {post: post} %></td>
                  <td>
                    <%= post.draft ? 'Draft' : 'Published' %>
                  </td>
                  <td><%= post.created_at.strftime("%Y-%m-%d %H:%M") %></td>
                  <td>
                    <%= render partial: "shared/edit_button", locals: { type: "Post", post: post } %>
                  </td>
              <% end %>
              </tr>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% if @user == current_user %>
      <%= link_to "New Post", new_post_path, class: "btn btn-info" %>
    <% end %>
  </div>
</div>