config/routes.rb
Rails.application.routes.draw do

  devise_for :user
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "posts#index"

     resources :posts do
       resources :comments, except: [:show]
       member do
         post :collect
         post :uncollect
       end
     end


      resources :users, except: [:index] do
        member do
          get :posts
          get :comments
          get :collects
          get :friends
          get :drafts
        end
      end

      resources :friendships, only: [:create, :destroy] do
        member do
          post   :accept
          delete :ignore

        end
      end

      resources :feeds, only: :index
      resources :categories, only: :show



     namespace :admin do
       resources :categories
       resources :users, only: [:index] do
         member do
          post :update
         end
       end
       root "categories#index"
     end

     namespace :api, defaults: {format: :json} do
       namespace :v1 do
         post "/login"  =>  "auth#login"
         post "/logout"  =>  "auth#logout"
         resources :posts, except: [:edit]
       end
     end

end

app/models/post.rb
class Post < ApplicationRecord
  # mount_uploader :image, PhotoUploader
  validates_presence_of :content, :title, :authority
  is_impressionable #:counter_cache => true, :column_name => :viewed_count

  belongs_to :user, counter_cache: true

  has_many :categories_posts
  has_many :categories, through: :categories_posts

  has_many :comments, dependent: :destroy

  has_many :collects, dependent: :destroy
  has_many :collected_users, through: :collects, source: :user

  # scope :open_public, -> { where(public: true) }


    def is_collected?(user)
     self.collected_users.include?(user)
    end



end

app/views/shared/_collect_button.html.erb
<% if post.is_collected?(current_user) %>
  <%= link_to 'Uncollect', uncollect_post_path(post), remote: true, method: :post, class: "btn btn-sm btn-info", id: "uncollect-#{post.id}" %>
<% else %>
  <%= link_to 'Collect', collect_post_path(post), remote: true, method: :post, class: "btn btn-sm btn-primary", id: "collect-#{post.id}" %>
<% end %>

app/views/shared/_content_item.html.erb
<div class="content-item w-100">
  <p><%= content %></p>
  <div class="row">
    <div class="col-sm-2 offset-sm-10">
      <% if type == "Post" %>
        <%= render partial: "shared/edit_button", locals: { type: type, post: post} %>
      <% else %>
        <%= render partial: "shared/edit_button", locals: { type: type, post: post, comment: comment} %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_edit_button.html.erb
<% if type == "Post" %>
  <div class="buttons">
    <% if post.user == current_user %>
        <%= link_to edit_post_path(post) do %>
          <button class="btn btn-info btn-sm glyphicon glyphicon-pencil"></button>
        <% end %>
    <% end %>
    <% if post.user == current_user || current_user.admin? %>
      <%= link_to post_path(post), method: :delete, data: {confirm: "Are you sure to delete this post?"} do %>
        <button class="btn btn-danger btn-sm glyphicon glyphicon-trash"></button>
      <% end %>
    <% end %>
  </div>

<% else %>
  <div class="buttons">
    <% if comment.user == current_user  %>
        <%= link_to edit_post_comment_path(post, comment) do %>
          <button class="btn btn-info btn-sm glyphicon glyphicon-pencil"></button>
        <% end %>
    <% end %>
    <% if comment.user == current_user || current_user.admin? %>
        <%= link_to post_comment_path(post, comment), method: :delete, data: {confirm: "Are you sure to delete this post?"} do %>
          <button class="btn btn-danger btn-sm glyphicon glyphicon-trash"></button>
        <% end %>
    <% end %>
  </div>
<% end %>

app/views/shared/_friend_button.html.erb
<% if user !=  current_user %>
  <% unless current_user.friend?(user) %>
    <% if current_user.request_friend?(user) %>
      <%= link_to "Accept friend request", accept_friendship_path(user), class: "btn btn-primary", method: :post, remote: true %><br>
      <%= link_to "Ignore friend request", ignore_friendship_path(user), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure to ignore the friend request?"}, remote: true %>
    <% elsif current_user.unconfirm_friend?(user) %>
    <% else %>
      <%= link_to "Send friend request", friendships_path(friend_id: user), class: "btn btn-primary", method: :post, remote: true %>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_friend_profile.html.erb
<div class="user-item text-center mt-3 mb-3">
  <%= link_to user_path(user), class: "nav-link" do %>
    <div class="avatar">
      <%#= image_tag user.avatar, width: "100%" if user.avatar? %>
      <%= filestack_image user.avatar, transform: filestack_transform.resize(width: 250, height: 250) %>
    </div>
    <p><strong><%= user.name %></strong></p>
  <% end %>

  <div class="links" id="user-<%= user.id %>">
    <%= render partial: "shared/friend_button", locals: { user: user } %>
  </div>
</div>

app/views/shared/_my_comments.html.erb
<!-- <td><%#= comment.content %></td>
<td>
    <%# if comment.user == current_user %>
    <%#= link_to edit_post_comment_path(comment.post, comment, site: "my_comments"), remote: true do%>
      <button class="btn btn-danger btn-sm glyphicon glyphicon-pencil"></button>
      <%# end %>
     <%#= link_to post_comment_path(comment.post, comment), method: :delete, data: { confirm: "Are you sure?"}, remote: true do%>
      <button class="btn btn-info btn-sm glyphicon glyphicon-trash"></button>
      <%# end %>
      <%# end %>
</td> -->

app/views/shared/_navtab_user.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-sm-12">
      <ul class="nav nav-tabs nav-fill">
        <li class="nav-item">
          <%= link_to_unless_current "My Post", user_path(user), class: "nav-link" do %>
            <%= link_to "My Post", user_path(user), class: "nav-link active bg-light" %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to_unless_current "My Comment", comments_user_path(user), class: "nav-link" do %>
            <%= link_to "My Comment", comments_user_path(user), class: "nav-link active bg-light" %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to_unless_current "My Collect", collects_user_path(user), class: "nav-link" do %>
            <%= link_to "My Collect", collects_user_path(user), class: "nav-link active bg-light" %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to_unless_current "My Draft", drafts_user_path(user), class: "nav-link" do %>
            <%= link_to "My Draft", drafts_user_path(user), class: "nav-link active bg-light" %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to_unless_current "My Friend", friends_user_path(user), class: "nav-link" do %>
            <%= link_to "My Friend", friends_user_path(user), class: "nav-link active bg-light" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_post_authority.html.erb
<% case post.authority %>
  <% when 'all'%>
    &nbsp;&nbsp;<i class="fa fa-globe post-authority"></i>
  <% when 'friend' %>
    &nbsp;&nbsp;<i class="fa fa-user-circle-o post-authority"></i>
  <% when 'myself' %>
    &nbsp;&nbsp;<i class="fa fa-lock post-authority"></i>
<% end %>

app/views/shared/_post_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 mt-4">
      <%= form_for @post do |f| %>
        <div class="form-group">
          <%= f.label :title, "Title" %>
          <%= f.text_field :title, placeholder: "Title", class: "form-control bg-light" %>
        </div>
        <div class="form-group">
          <%= f.label :content, "Post" %>
          <%= f.text_area :content, placeholder: "What's on your mind?", class: "form-control bg-light" %>
        </div>
        <div class="form-group">
          <%#= f.file_field :image %>
          <%= f.filestack_field :image, 'Upload Your Photo!',  pickerOptions: { accept: 'image/*'} %>
        </div>
        <div class="form-group">
          <label> Who can see </label>
          <div class="form-check form-check-inline">
            <%= radio_button :post, :authority, "all", { checked: true , class: "form-check-input" } %>
            <%= label_tag :authority_All, "All", class: "form-check-label" %>
          </div>
          <div class="form-check form-check-inline">
            <%= radio_button :post, :authority, "friend", class: "form-check-input" %>
            <%= label_tag :authority_Friend, "Friend", class: "form-check-label" %>
          </div>
          <div class="form-check form-check-inline">
            <%= radio_button :post, :authority, "myself", class: "form-check-input" %>
            <%= label_tag :authority_Myself, "Myself", class: "form-check-label" %>
          </div>
        </div>
        <div class="form-group">
          <div><%= f.label :category, 'Category' %></div>
            <div class="checkbox-panel">
              <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name, {multiple: true} ) %>
            </div>
        </div>
        <div class="form-group">
           <% if post.draft == false && post.title.present? %>
             <%= f.submit 'Update', class: "btn btn-primary" %>
           <% else %>
             <%= f.submit 'Save Draft', class: "btn btn-info" %>
             <%= f.submit 'Submit', class: "btn btn-primary" %>
           <% end %>

        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_post_item.html.erb
<% if type == "Post" %>
  <div class="col-sm-3 border">
    <%= render partial: "shared/friend_profile", locals: { user: post.user } %>
  </div>
  <div class="col-sm-9 border">
    <div class="image mt-3">
      <%#= image_tag post.image, width: "500px" if post.image? %>
      <%= filestack_image post.image, transform: filestack_transform.resize(width: 400, height: 400) %>
    </div>
    <%= render partial: "shared/content_item", locals: { type: type, post: post, content: post.content } %>
  </div>
<% else %>
  <div class="col-sm-3 border">
    <%= render partial: "shared/friend_profile", locals: { user: comment.user } %>
  </div>
  <div class="col-sm-9 border d-flex align-items-center">
  <%= render partial: "shared/content_item", locals: { type: type, post: post, comment: comment, content: comment.content } %>
  </div>
<% end %>

app/views/shared/_reply_comment.html.erb
<div>
  <%= comment.content %>
</div>

app/views/shared/_user_profile.html.erb
  <div class="container bg-light">
    <div class="row pt-3">
      <div class="col-sm-12">
          <div class="row">
          <div class="col-sm-3 mt-3">
            <%= link_to user_path(user), class: "nav-link" do %>
              <%#= image_tag user.avatar, width: "100%" if user.avatar? %>
              <%= filestack_image user.avatar, transform: filestack_transform.resize(width: 250, height: 250) %>
              <p class="text-center"><strong><%= user.name %></strong></p>
            <% end %>
          </div>
          <div class="col-sm-9">
            <p><%= user.intro %></p>
            <% if user == current_user %>
              <div class="d-flex flex-row-reverse">
                <%= link_to "Edit", edit_user_path(user), class: "btn btn-info" %>
              </div>
            <% else %>
              <div class="d-flex flex-row-reverse" id="user-<%= user.id %>">
                <%= render partial: "shared/friend_button", locals: { user: user } %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>