config/routes.rb
Rails.application.routes.draw do

  devise_for :user
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "posts#index"

     resources :posts do
       resources :comments, except: [:show]
       member do
         post :collect
         post :uncollect
       end
     end


      resources :users, except: [:index] do
        member do
          get :posts
          get :comments
          get :collects
          get :friends
          get :drafts
        end
      end

      resources :friendships, only: [:create, :destroy] do
        member do
          post   :accept
          delete :ignore

        end
      end

      resources :feeds, only: :index
      resources :categories, only: :show



     namespace :admin do
       resources :categories
       resources :users, only: [:index] do
         member do
          post :update
         end
       end
       root "categories#index"
     end

     namespace :api, defaults: {format: :json} do
       namespace :v1 do
         post "/login"  =>  "auth#login"
         post "/logout"  =>  "auth#logout"
         resources :posts, except: [:edit]
       end
     end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # mount_uploader :avatar, AvatarUploader

  validates_presence_of :name, :email

  before_create :generate_authentication_token

  has_many :posts, dependent: :destroy

  has_many :comments, dependent: :destroy
  has_many :commented_posts, through: :comments, source: :post

  has_many :collects, dependent: :destroy
  has_many :collected_posts, through: :collects, source: :post

  has_many :friendships, -> {where status: true}, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :inverse_friendships, -> {where status: true}, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_friendships, source: :user
  has_many :unconfirm_friendships, -> {where status: false}, class_name: "Friendship", dependent: :destroy
  has_many :unconfirm_friends, through: :unconfirm_friendships, source: :friend
  has_many :request_friendships, -> {where status: false}, class_name: "Friendship", foreign_key: "friend_id", dependent: :destroy
  has_many :request_friends, through: :request_friendships, source: :user

  def admin?
    self.role == "admin"
  end

  def all_friends
    friends = self.friends + self.inverse_friends
    return friends.uniq
  end

  def friend?(user)
    self.friends.include?(user) || self.inverse_friends.include?(user)
  end

  def unconfirm_friend?(user)
    self.unconfirm_friends.include?(user)
  end

  def request_friend?(user)
    self.request_friends.include?(user)
  end

  def generate_authentication_token
    self.authentication_token = Devise.friendly_token
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
    @users = User.page(params[:page]).per(10).order("created_at DESC")

  end

  def update
    @user = User.find(params[:id])
    @user.role = params[:role]
    @user.save!
    flash[:notice] = "User role was successfully changed !"
    redirect_back(fallback_location: admin_users_path)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :comments, :collects, :friends, :check_user, :drafts]
  before_action :set_posts
  before_action :check_user, except: [:show, :comments]

    def show

    end

    def edit

    end

    def update
     if @user.update(user_params)
       redirect_to user_path(@user)
     else
       render :action => :edit
     end
    end

    def comments
      @comments = @user.comments.includes(:post)
    end

    def collects
      @collected_posts = @user.collected_posts.includes(:collected_users)
    end

    # def drafts
    #   @drafts = @user.posts.where(public: false)
    # end

    def friends
      @friends = @user.all_friends
      @unconfirm_friends = @user.unconfirm_friends
      @request_friends = @user.request_friends
    end

private

   def set_user
    @user = User.find(params[:id])
   end

   def user_params
     params.require(:user).permit(:name, :intro, :avatar)
   end

   def check_user
     unless @user == current_user
       flash[:alert] = "You have no authority！"
       redirect_to user_path(@user)
     end
   end

   def set_posts
     @posts = Post.where(user_id: @user.id)
   end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container">
   <div class="row">
     <ul class="nav nav-tabs nav-fill">
       <li class="nav-item">
         <%= link_to_unless_current "Category List", admin_categories_path, class: "nav-link" do %>
           <%= link_to "Category List", admin_categories_path, class: "nav-link active bg-light" %>
         <% end %>
       </li>
       <li class="nav-item">
         <%= link_to_unless_current "User List", admin_users_path, class: "nav-link" do %>
           <%= link_to "User List", admin_users_path, class: "nav-link active bg-light" %>
         <% end %>
       </li>
     </ul>
   </div>
 </div>
 <br>
 <div class="container">
   <div class="row">
     <table class="table table-hover">
        <thead class="thead-light">
           <tr>
             <th>ID</th>
             <th>User Name</th>
             <th>Email</th>
             <th>Introduction</th>
             <th>Role</th>
             <th>Change Role</th>
           </tr>
         </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <th scope="row"><%= user.id %></th>
              <td><%= link_to user.name, user_path(user) %></td>
              <td><%= user.email %></td>
              <td><%= user.intro %></td>
              <td><%= user.role %></td>
              <td>
               <%= form_tag(admin_user_path(user.id), :method => 'post') do  %>
                  <div class="input-group">
                    <%= select_tag('role', options_for_select([['Admin', 'admin'], ['Normal User', 'normal']], user.role == 'admin' ? "admin" : "normal") )%>
                    <%= submit_tag "Update" %>
                  </div>
               <% end %>
             </td>
            </tr>
          <% end %>
         </tbody>
        </table>
       <div class="m-auto">
       <%= paginate @users %>
       </div>
    </div>
  </div>