config/routes.rb
Rails.application.routes.draw do

  devise_for :user
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "posts#index"

     resources :posts do
       resources :comments, except: [:show]
       member do
         post :collect
         post :uncollect
       end
     end


      resources :users, except: [:index] do
        member do
          get :posts
          get :comments
          get :collects
          get :friends
          get :drafts
        end
      end

      resources :friendships, only: [:create, :destroy] do
        member do
          post   :accept
          delete :ignore

        end
      end

      resources :feeds, only: :index
      resources :categories, only: :show



     namespace :admin do
       resources :categories
       resources :users, only: [:index] do
         member do
          post :update
         end
       end
       root "categories#index"
     end

     namespace :api, defaults: {format: :json} do
       namespace :v1 do
         post "/login"  =>  "auth#login"
         post "/logout"  =>  "auth#logout"
         resources :posts, except: [:edit]
       end
     end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Article Forum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= filestack_js_include_tag %>
    <%= filestack_js_init_tag %>
  </head>
  <body>  
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <%= link_to "Forum", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Feeds", feeds_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "All Post", posts_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "New Post", new_post_path, class: "nav-link" %>
            </li>
          </ul>
          <ul class="pull-right text-right navbar-nav">
            <% if current_user %>
              <% if current_user.admin? %>
                <li class="nav-item">
                  <%= link_to "Admin" , admin_root_path, class: "nav-link" %>
                </li>
              <% end %>
              <li class="nav-item">
                <a class="nav-link" href="">
                  <%= current_user.email %>
                  (<%= current_user.role.capitalize %>)
                </a>
              </li>
              <li class="nav-item">
                <%= link_to "Profile" , user_path(current_user), class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <a class="nav-link" href="">Hi, Guest</a>
              </li>
              <li class="nav-item">
                <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
          <% if flash[:notice] %>
            <div class="container">
              <div class="row">
               <div class="alert alert-success alert-dismissible" role="alert">
                 <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <%= notice %>
               </div>
              </div>
            </div>
          <% end %>
          <% if flash[:alert] %>
            <div class="container">
                <div class="row">
                  <div class="alert alert-danger alert-dismissible" role="alert">
                   <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <%= alert %>
                  </div>
                 </div>
               </div>
            <% end %>
         <%= yield %>
  </body>
</html>